### PR TITLE
Added Simon says skill

### PR DESCRIPTION
**Pull request by DevelopingUnicorn**
Added a simon says skill!

### CODE REVIEW

**Comment by timstableford** [comment]
I'm curious whether this is always classified correctly. Like if I said to Brain "Simon Potato says", would it bomb out because it's classified as simonsays but has nothing after says?
From personal experience I've also found that when supplying an unknown number of words to a skill it's better to use the hard_rule function rather than intents. Otherwise "Simon says tell me the time" is quite likely to tell me the time rather than be a simon says.

**Comment by patrickjquinn** [comment]
Hi @DevelopingUnicorn can you elaborate on the purpose of this skill?

**Comment by DevelopingUnicorn** [comment]
@timstableford I will use hard_rule thx for the suggestion!
@patrickjquinn It's sort of a fun skill, not usefull at all. Maybe for something like you use the P-Brain app to tell your client at home to say something. For example to tell the kids to do their homework or something similar. At this state of the skil it just repeats what comes after "Simon says".

**Comment by patrickjquinn** [comment]
Okay that sounds cool! I'll merge this now 👍

**Comment by timstableford** [comment]
@patrickjquinn, @DevelopingUnicorn never switched to using the hard_rule method so this may cause some issues. Probably not though.

**Pull request merged**
