### PR TITLE
Added authentication

### PR DESCRIPTION
**Pull request by timstableford**
Hi Patrick,

Here's a first pass of doing authentication with tokens. I haven't figured out an elegant way to turn it off, so it's always on. There's a default user with the username demo and password demo. There's also a script called password.js to generate passwords in the format required for config/users.json.

I don't think we should merge this into master until we find a way for the demo to work without prompting when a user first downloads it, that and we'll both have to update the various apps first. Additionally, tokens do not currently persist across server reboots.

New API's:
/api/validate?token=<token> - returns HTTP status 200 if a token is valid.
/api/login - Required HTTP basic auth username and password, returns {token: "<token"} and status code 200 on success. This also creates a new token which persists until server start.

The socket.io handshake should be done with a token parameter ?token=<token>.

The flow when authenticating should be:
- If you have no stored token, then login.
- If you have a token, attempt to validate it.
- If valid, setup Socket.IO if not valid, login.

### CODE REVIEW

**Comment by patrickjquinn** [comment]
Okay I wont merge it just yet, my suggestion would be to checkout my user_profiles branch which has a local filesystem based structure that will allow persistence without a 3rd party DB required. Funny that we decided to work on opposite ends of this at the same time!

**Comment by timstableford** [comment]
Looking at the [diskdb source](https://github.com/arvindr21/diskDB/blob/master/lib/collection.js#L61) I still have concerns that for a large database it won't do well.

Either way there's only a very basic user management in this PR and merging these changes together would fit surprisingly well for something that wasn't planned.

If you don't have any issues with the changes in this PR, I'd say test it thoroughly and then feel welcome to pull it into your branch but I still would prefer to avoid putting it into master until all the clients are fixed :+1:

**Comment by patrickjquinn** [comment]
I'll keep it out of master till its stable (i've not been smart enough to tag my releases like you did with the Android client). 

My gut feeling (usually wrong, sometimes right) is that most people will be using this locally on their own machine and for the moment we will be the only ones hosting this anywhere. If performance degradation arises the database can simply be imported straight into say, mongo, without any changes. At this point the question is, add a db as a dependency or stick with fs based data structures.

**Comment by timstableford** [comment]
I'd vote for adding db, or going broader I'd vote for a relational database instead.

Thinking about it, we could just keep all of the multi-user stuff on a branch to keep the project more accessible?

**Comment by patrickjquinn** [comment]
db makes a ton of sense, relational dbs are not 'noobie friendly' (the only people who know SQL are computer scientists and PHP developers, but dont quote me on that). There are some blazing fast noSQL dbs out there.

Instead of splintering this project into concurrent branches, why not add a runtime argument i.e `--with_db` or something so if people want databases they can have them, all under the one project.

**Comment by timstableford** [comment]
I wasn't so much thinking of splitting for making setup easier, more for making the code more accessible. I think a lot of the charm is that the core code is easy to understand.

**Comment by timstableford** [comment]
You're probably right that having it in master is the best plan. I think we should keep only one option though and just always use a DB

**Comment by patrickjquinn** [comment]
Yep thats why consideration is really important here, we need to keep this as simple as is humanly possible and any new feature is a potential new layer of complexity. So what is the simplest solution here?

So decision time, i'd prefer something like CouchDB over Postgres or MySQL or something. Everyone understands JSON so whatever we choose it should probably be JSON based. 

Whats your take?

**Comment by patrickjquinn** [comment]
Here is an idea. Considering we are using JSON files anyway, why not just use the diskdb module for the moment (which has the exact same api structure as mongo and couch) and centralise it into a single 'db' module for all r/w operations. Then when it comes time to implement the database changes, we can just change the require (give or take) in that module and everything should just work.

Feel free to tell me to F off on this one, I just have the above stuck stubbornly in my noggin.

**Comment by timstableford** [comment]
My inner geek says SQLite because this really is quite relational data but you're probably right about accessibility. I think using dbdata in the way you've suggested could work well. The format you've suggested in the branch though I think we could make more relational.

I think there should be separate tables for users, responses, queries and tokens. Where the responses, queries and tokens would contain the user ID that they're related to.

Definitely put all these database functions accessible in a single interface with accessor methods like addUser, getUser, addToken, removeToken etc so we can change it later.

**Comment by patrickjquinn** [comment]
Okay i'll add all of those methods and merge your token changes into the user_profiles branch (or whatever I called it)

**Comment by timstableford** [comment]
I just read your comment about hand merging. You know you could've added my repository as a remote and then pulled it into your branch right? Anyway, if it's merged in, feel free to close this PR.

**Comment by patrickjquinn** [comment]
Yep tried that, got a conflict sadly, so just merged manually. It was just small enough to merge by hand so I did, also allowed me to take a closer look at your code 😊It's good stuff.

**Comment by timstableford** [comment]
Phew, glad you didn't have to do all the work for nothing :) If you're willing to give me write access to your repo I'll help work on that branch with you if you like?

**Comment by patrickjquinn** [comment]
No no, with the number of great contributions you're making I need to make sure i'm totally on top of everything! It was a great exercise!

I've granted you full repo access! No need run pushes by me, maybe just create a ticket if what you're working on is a monumental change, otherwise fire at will!

Also if you need to get in touch with me directly, either pat64.ai@gmail.com or via our gitter channel https://gitter.im/P-Brain/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge :)

**Pull request closed without merging**
