### PR TITLE
Remove yarn.lock and refactor to better suit msg: {text: 'text'} format

### PR DESCRIPTION
**Pull request by timstableford**
A relatively small PR for you.

- Removed yarn.lock
- Changed the return format of many skills to better use objects rather than text parsing.
- Changed display_response to either accept raw messages or just text, and moved usage to this from push_response.
- Changed the Youtube skill to return the title of the video it found.

### CODE REVIEW

**Comment by patrickjquinn** [comment]
I love a lot of this, but bear in mind that every time the server response format changes, every client (the iOS, RasPi and Web clients) must be updated to accomidate it, this shouldn't break much but for future contributions if every could be aware of this i'd really appreciate it 👍 

Before I merge, has this passed the unit testing and has it been personally tested by yourself? :) I've gone through it line by line but short of pulling down your branch to test my self, I cant be sure!

Thanks for this!

**Comment by timstableford** [comment]
Apologies for changing the format a second time. After the first PR I had no idea you were going to change the formats of them all or I would have changed them there :) On the bright side it was only the formats for youtube, movie and timer skills.

Looking the timer skill in the ras pi client I think it might already be broken because it doesn't use the parsing I switched to in the previous PR. Nothing else should be effected there though.

I didn't actually know there was an iOS client, are there plans to make an Android one too?

I might need some instructions on running unit tests, I can only find one test in the source? Other than that I've tested each of the skills to ensure they still function by doing a few different queries.

**Comment by timstableford** [comment]
In a future PR I'd like to move the timer functions to server side but that poses a whole host of issues. Such as polling the server for updates or using socket.io for communication and allowing skills to broadcast updates. I think it'd be quite a cool feature to be able to start a timer on one device and receive a notification on another. I also think if we did this we could make the client side more generic in the future.

**Comment by patrickjquinn** [comment]
Yes indeed :) I'm trying to abstract the clients from the server as much as possible, I love the idea of moving the timer server side and add a socket.io based server side push! we would need to have a connected device register so we can send push between different devices. i.e 'Play x by y in the living room' for example.

I changed all of the skill responses because it was the better way of doing it and added more options for client handling and less messy parsing on the client side!

Thanks for this! I'm happy to merge the PR 👍

**Comment by patrickjquinn** [comment]
Also there isnt much on the unit testing front yet but `node test` should do the job 👍  and your method of testing is more adequate! 

I'd suggest running `npm i -g xo` and then `xo ./*/* --no-semicolon  --esnext --env=node --env=mocha --fix --space=4`

To make sure that the project remains in line with ES2015 standards.

**Comment by patrickjquinn** [comment]
As for the clients, iOS client is totally functional but 90% of the code lives in a single view controller and is pretty hacked together, I want to clean a lot of that up before I push it to GitHub 👍  No plans for an Android app, i've no built anything properly for Android since Ice Cream Sandwich so my Java/Android abilities are...rusty to say the least.

I've attached a screenshot of the iOS app in action! 
image-2

**Comment by patrickjquinn** [comment]
I'm noticing that the speech recognition "annyang" seems to start and stop since this PR, any idea what could be causing this?

**Comment by patrickjquinn** [comment]
^ that's on the web client by the way :)

**Comment by timstableford** [comment]
Are you sure it was this PR? I noticed it before this I think? If it were any of my changes I'd think it would be the name ones in the previous PR

**Comment by patrickjquinn** [comment]
Either this or the last one, none before that have modified annyang or the web client, i'll try reverting the index and seeing if it fixes it!

**Comment by patrickjquinn** [comment]
Yep, it was the addition of the setup function that broke annyang (it can be a little bit...finicky), i'll modify the original index.html and merge in your changes 👍

**Comment by timstableford** [comment]
Thanks. Sorry about the bug. Just for future reference did you find out why putting it in a function causes this weird behaviour?

**Comment by patrickjquinn** [comment]
Didnt find anything concrete, seems to be the render order, the fact that annyang isnt started until `xmlhttp.onreadystatechange = function` returns seems to be what is causing the issue, obviously we need that for the name so i'm working on a work around (possibly similar to how ip is gotten now) :)

**Comment by timstableford** [comment]
I've been playing around and adding aanyang.init({}, false); before setup seems to improve things.

**Comment by patrickjquinn** [comment]
Momentarily till the callback kicks in, i'll keep digging :)

**Comment by timstableford** [comment]
This seems to completely do it?
```javascript
        annyang.init({}, true);

        SpeechKITT.annyang();
        SpeechKITT.setStylesheet('themes/flat.css');
        SpeechKITT.vroom();
        function setup() {
```

**Comment by patrickjquinn** [comment]
not on my end sadly, just seems to last a little longer before the speech bar closes again. Is the above working for you?

**Comment by timstableford** [comment]
It is. Speech bar hasn't done anything weird since setting it to that. Running Chrome on Ubuntu. (I also removed those calls from further down so they're only before setup)

**Comment by timstableford** [comment]
Here's my full [index.html](https://github.com/timstableford/P-Brain.ai/blob/master/src/index.html) in case there's any other things in mine that made a difference.

**Comment by patrickjquinn** [comment]
Yep It works on my end, removing the duplicate init and configuration calls done after the get request returns. 

I'll push this alteration now!

**Comment by timstableford** [comment]
That's great news! :) 
I also noticed we don't remove the voice commands from the previous name so it would continue to respond to old names until a refresh currently.

**Comment by patrickjquinn** [comment]
I've done a refactor so it doesn't try and start speech recognition on an unsupported device. I'll dig into the annyang docs and see if you can reset on name change

**Pull request merged**
