### PR TITLE
Better Speech Classification

### PR DESCRIPTION
**Pull request by timstableford**
Hi Patrick,

I went to add some new skills but it got frustrating getting everything to recognise correctly so I've implemented your suggestion of of using responses.json for additional training data, along with added examples to each of the skills with a re-education if verification fails for an example.

I think this could still use some additional tweaks here and there so let me know what you think. I've also started an Android app for P-Brain, I don't suppose you have an icon I can use?

Change list:
- Moved the greeting to server side.
- Added a skill to learn the users name, this is then used in the greeting skill.
- Made it possible for skills not to have intents, such as the greeting module.
- Improved the register and registerClient functions to make them yieldable.
- Adding an API to re-train if a command is incorrect /api/correct_last/:skill_name. This currently doesn't verify the other modules, but it is done on restart.
- Using responses.json for additional classification examples.
- Added examples to each skill which are tested and trained against on start.
- Allow timer to execute queries.

### CODE REVIEW

**Comment by patrickjquinn** [comment]
Wow, you're contributing more to this project than I am! Thank you 👍 . I'll give it a solid code review now and see if I cant find anything to improve, probably not but its worth looking over.

Thank you for putting together an Android app too, its something I was heavily considering but didnt think i'd have the time! Let me know if you need a second pari of eyes on it. I've attached the icon i've been using for the iOS client. Its in proper Android format so you should just be able to drag it in to intelli j as is!  

Hope that helps :)
[android.zip](https://github.com/patrickjquinn/P-Brain.ai/files/753101/android.zip)

**Comment by timstableford** [comment]
Thanks :) Since this PR I've discovered that adding so many additional responses causes a bias away from other commands in the skill. So expect an update where I just keep the examples in, unless you have any ideas?

**Comment by patrickjquinn** [comment]
My suggestion would be to remove any pronouns and adverbs ("who what where, is and the etc) from the training data unless they are keyword to be recognised, the more distinctive the keywords the higher (well...lower, but you get what I mean)  the confidence. Beyond that I'll have to dig into Natural and see if there is a better training method! Training is a great addition, the more learning added to this project, the closer it gets to actual AI :)

**Comment by timstableford** [comment]
I might try that, I'm going to switch to the going the Android app for a while now. I'm concerned that removing those words will lose the structure of some of the classifications? (If that makes sense). For now I've made responses.json only be used if a config option is set.

This set of commits also adds the ability for the timer to execute commands on completion. So something like "In 10 seconds tell me the weather" will execute "tell me the weather". I think this would work really well with a simple skill for reminders.

**Comment by patrickjquinn** [comment]
This code look good, i'm going to merge it and see if I can improve classification accuracy without breaking the sentence structure (maybe splitting the various training sentences into smaller sub-strings as objects in the array, we will see what works best)

Let me know if you need any input on the Android app 👍

**Comment by timstableford** [comment]
I wish you luck! I've invited you to be a collaborator on the Android app should you feel like doing any Android dev. Do you have an icon with a transparent background that would still stand out on screens with darker colour schemes? This might be asking a bit much but I'm terrible at graphics and UI design from an aesthetic perspective.

**Comment by patrickjquinn** [comment]
No problem i'll generate a transparent one now :) Give me two minutes!

**Comment by patrickjquinn** [comment]
[android.zip](https://github.com/patrickjquinn/P-Brain.ai/files/753162/android.zip)

Thats the icon with a transparent background 👍  Let me know if you wanted it with the colours inverted or anything.

**Pull request merged**
