### PR TITLE
Added multiple device support

### PR DESCRIPTION
**Pull request by timstableford**
Hi Patrick,

Nice big API additions are per usual it seems to me. This adds multi-device support. For examples on exercising the multi-device feature, check out the new skill.

Changelist:
- Fixed query parsing not passing stripped/lower-cased queries to skills.
- Added tokens/devices passed with each query.
- Added multi-device skill.

### CODE REVIEW

**Comment by gunnarvingren** [comment]
Hi, 
Im trying to use the IoT_url skill to send a local IP command to a light (192.168.1.107:8080/kitchenlight). 
Im fairly new to this coding and Github stuff. Can you show me an example (index.js) using my local IP address and saying (Kitchen Light) as the voice command? 
Thank you and sorry for the noob questions... 

(I dont even know if this is the right place to write this request :0 )

**Comment by timstableford** [comment]
Hello,
The instructions for setting up the ts_iot are in ts_iot/index.js and the Wiki. That said they're a bit scattered.

First thing is URL formatting, "kitchenlight" should be "kitchen_light" (Brain translates spaces to underscores) and your end point should also have an on and off function. Something like:
- http://192.168.1.107:8080/kitchen_light/on
- http://192.168.1.107:8080/kitchen_light/off

To use a URL like this with the IoT module you need to set the skill setting for ts_iot to: _http://192.168.1.107:8080/%s/%s_. That can be done by URL encoding that to _http%3A%2F%2F192.168.1.107%3A8080%2F%25s%2F%25s_ and using the setting REST API to set it.

So on your PBrain server navigate to:
_/api/settings/skill_setting/ts_iot/url?value="http%3A%2F%2F192.168.1.107%3A8080%2F%25s%2F%25s"_

And everything should be working, assuming the on and off methods are implemented :)
It should respond to commands like "Turn on the kitchen light", "Turn the kitchen light off".

**Comment by gunnarvingren** [comment]
Timstableford, 

Thank you for the reply. 
To be honest with you the URL coding part just made everything a little more confusing for me.. 
Im very crude on the coding part. But I don't mean to waste your time with this. Just wanted to get a better understanding of what to replace on the existing skill index.js.

Currently my kitchen_light command is a scene toggle command. (turns the light on if it is off or turn it off if it is on). So I dont really need the ON of OFF state. All I need it to do is to trigger the URL and confirm the command with a phrase (i.e.: Kitchen light active). 
 
 Once again sorry for the Noob questions. 

Thank you!

**Comment by timstableford** [comment]
If you were to do it the way I suggested you wouldn't have to make any changes. As it stands you'll have to change a significant amount more than I imagine you're suspecting.
What you want to do is significantly different to the ts_iot skill. I recommend you make a new skill that in the _hard_rule_ function checks for 'toggle the kitchen light' and then in the _get_ function simply invokes your URL. That's definitely the easiest way other than adding an on/off function.

**Comment by gunnarvingren** [comment]
That's what i figured.. It really had to be something much more simpler than what I was reading on the ts_iot skill readme file. 
Is there instructions for ignorant people like me on how to create a new skill? 
or maybe you could write it and send it to me. (I have no problem supporting your work financially).

**Comment by gunnarvingren** [comment]
lol you probably gonna laugh at me... but i kind got to this point. 

const request = require('co-request')
const intent = () => ({
    keywords: ['kitchen'],
    module: 'kitchen'
})

function * kitchen_resp(query) {
    const kitchen_url = 'http://192.168.1.107:8080/kitchenlight'
    let data = yield request(kitchen_url)
	let response = 'Looks like , better wear '
    return {text: data.value}
}

const examples = () => (
    ['kitchen', ]
)

module.exports = {
    get: kitchen_resp,
    intent,
    examples
}


It is activating the scene but I cant get "Brain" to say what I want it to say after the command. It is saying "Object, object"... any thoughts?

**Comment by patrickjquinn** [comment]
You should add 'console.log (JSON.stringify (data))' before you return in
your request function. This will give you the actual property you should be
returning Instead of just data.text

**Comment by gunnarvingren** [comment]
Something like this? 

function * kitchen_resp(query) {
    const kitchen_url = 'http://192.168.1.107:8080/kitchenlight'
    let data = yield request(kitchen_url)
	return  'console.log (JSON.stringify (data))' {text: data.value}
}


If I want to get more deep into this programming language and actually learn it. Where do you recommend me to start with? and what language is this anyways? 
Thanks

**Comment by timstableford** [comment]
I think what Pat's trying to say is that data.value isn't a string/text type. It's likely something else. It looks like you just want Brain to say kitchen scene activated. So just replace _return {text: data.value}_ with _return {text: response}_

**Comment by timstableford** [comment]
This language is NodeJS which is essentially Javascript with some extra bits and pieces. Just give a beginners tutorial for NodeJS a Google.

**Comment by gunnarvingren** [comment]
Yep.. That's it. Thank you for the help.

function * kitchen_resp(query) {
    const kitchen_url = 'http://192.168.1.107:8080/kitchenlight'
    let data = yield request(kitchen_url)
    let response = 'Kitchen Scene Active'
    return {text: response}
}

Now, will this be the same procedure to have this working on a RaspberryPi?

**Comment by timstableford** [comment]
@gunnarvingren The same should work on the Pi. Only the server needs to be updated, which you've done. In future, if you have issues with the project would be mind creating an issue under the Issues tab please?

@patrickjquinn Have you had a chance you give this a look over? :)

**Comment by patrickjquinn** [comment]
Sorry Tim, i've been busy with work, took a look over this and i'm very confident in the code, is it safe to merge?

**Comment by timstableford** [comment]
Hi Pat, should be safe to merge now I've pushed up that fix. If you get time though, do try run the branch on your local copy and do a few restarts. It would be good to sanity check the update process.

**Pull request merged**
