### PR TITLE
Auth, Multi-user and Database

### PR DESCRIPTION
**Pull request by timstableford**
This PR adds a load of changes to the backend. Notably adding a centralized data store, multi-user capability and authentication.

Changelist:
- Added socket.io authentication using tokens.
- Added user handling to queries, and updated relevant queries to be user aware.
- Added registration system for sockets connected by a specific user.
- Switched many links in the web client to https to fix mixed content warnings when proxying over HTTPS/Apache.
- Added SQLite database with a reasonably abstracted interface for easy drop in of other DB's.

### CODE REVIEW

**Comment by timstableford** [comment]
Updated password.js to add users and update passwords.

**Comment by timstableford** [comment]
We might want to add a "promiscuous" mode in the future. Where when a user is asked to login, if the user does not exist, it's created. Mainly thinking for the shared instance.

**Comment by patrickjquinn** [comment]
Yep, if the username isnt found, automatically create user, I was planning on doing this for iOS, where the username would be userset and the password would be the UUID of the device, that way we can tie a user account to a device (just a thought on my end). Happy with this and going to merge! GREAT work 👍

**Comment by timstableford** [comment]
I personally prefer the idea of manual entry, it would make it easier for the user to switch between different clients :) As to tying an account to a device, it might be better done with an extra field in with the tokens list?

**Comment by patrickjquinn** [comment]
yep it was just a passing thought on my end, not something i'm hugely concerned about on the iOS client for now (Just got Snoyboy working on iOS, their C++ interface is monstrously leaky)

**Comment by patrickjquinn** [comment]
Am i good to remove the two major auth branches?

**Comment by timstableford** [comment]
That's great news! :+1: Their Java interface is also a bit of a mess too. Yep, go ahead and remove them.

**Pull request merged**
