### PR TITLE
IoT Skill And Windows Compilation Fix

### PR DESCRIPTION
**Pull request by timstableford**
Hi Patrick,

Another PR. This one fixed windows compilation by moving away from node-expat. (It also now seems to run with a npm install instead of yarn).

I've also added an IoT skill. I've made it as generic as I can so users can replace it with whatever they're doing but it still isn't that useful on its own. Let me know if you want it removed from this PR.

### CODE REVIEW

**Comment by patrickjquinn** [comment]
This is excellent, i'm going to merge this right now. Just one note regarding the statically defined IP address you have in the IoT skill; i'm thinking of introducing the idea of local 'config.js' files in individual skills, so any configuration pertaining to a skill lives there. All modular, all self contained :)

**Comment by timstableford** [comment]
Maybe we should use the database module to provide key:value storage for the skills? Maybe centralised is better, I'm not sure.

**Comment by patrickjquinn** [comment]
The idea would be to keep it centralised, so you can just drop in a new skill in folder form, and have the system automatically recognise it. It's the path of least resistance me thinks.

**Comment by timstableford** [comment]
Well we could already do that part can't we? My full thought was to pass the database in as a parameter in the register method, then the module would drop its default config into there if necessary. There's just something that oddly irks me about making this mega-database we're planning and then not using it. Plus if we had the skills use the central database, then I think it would be quite easy to have skills have per-user configuration?

**Comment by patrickjquinn** [comment]
Yep that's what we are currently doing, it would make sense to register an "installed" skill in the database, for that particular use, that way we can allow toggling of skills, for that user, from the client

**Comment by timstableford** [comment]
Not quite what I meant but I do agree we should also do that. I was thinking that the config.json's you wanted to store in the skill folders should be in the database :)

**Comment by patrickjquinn** [comment]
Ah okay,  well we would need to do something to make it modular, last thing we need is the skill user having enter a config manually (or even programatically) entering keys and endpoints into a database themselves.

**Comment by timstableford** [comment]
Hmm, the database class could have methods such as:
function setValue("skill-name", user, key, value)
function getValue("skill-name", user, key)

(By database class I mean your db/index.js)

**Pull request merged**
