### PR TITLE
Expanded timer, name setter and cleanup

### PR DESCRIPTION
**Pull request by timstableford**
This PR covers a few different areas and features that you may want in your repo (or may not).

- Cleans up various stored files, logs, ip.js, classifier.json. They're now deleted and created on run. The classifier was re-created each run so the saved version was overwritten if I understood that right.
- Refactors how skills are loaded to allow them to register routes with express.
- Improves the timer functionality. Multiple timers, better parsing. Now supports multiple units such as "Set a timer for 10 minutes and 30 seconds."
- Adds the ability to change the name through a query and stores this value.

### CODE REVIEW

**Comment by patrickjquinn** [comment]
This work looks fantastic, fairly sizeable changes to the server so its going to take me an hour or two to go through it line by line (To make sure I know whats going on so I can convey stuff properly  in future videos etc).

One quick question, in the skills, another contributor changed `intent: _intent` (which I originally had) over to just exporting `intent`. Whats are the benefits to doing it your (and my original) way?

**Comment by patrickjquinn** [comment]
Also, in `core-ask.js`I added saving to and retrieving a local classifier.json so in future, manual training could be added i.e 'Hey brain that was wrong' in which brain would response 'Which skill should it have been?' and it could re-train for that specific query and save the resulting classifier for further use. It doesnt need to be there at the moment, just giving you a heads up as to my thinking behind that methodology 👍

**Comment by timstableford** [comment]
Going over it line by line is a good plan. Code reviews always appreciated. Feel free to add some comments if there's anything you disagree with.

I suspect he did that because in ES6 you can replace code like:
```javascript
{
  intent: intent
}
```
with just:
```javascript
{
  intent
}
```
Personally I prefer the old explicit way of doing it, but going fully with ES6 if we're using some features does make sense.

**Comment by timstableford** [comment]
That seems like an excellent idea for the classifier. I had to remove asking what the current name was because the fact module wouldn't be used with "what qqqq?" questions.

**Comment by patrickjquinn** [comment]
Yep I prefer a clearly defined map as you've stated above but didn't want to break from convention. If it has no functional difference i'm more than happy to do either or. 

I'll add any comments to commits i'm unsure of, although your changes are giving me ideas for further improvements! 

Ah yes, I knew there was going to be conflicts with keywords, especially vague ones like those used in the fact skill, with other skills There will need to be a better, more sturdy way of doing this across skills in future but I think you did the right thing here.

**Comment by patrickjquinn** [comment]
Okay I like this and think I'm happy to merge it! Thanks for this!

**Pull request merged**
