### PR TITLE
This project works fine with npm too

### PR DESCRIPTION
**Pull request by syzer**

### CODE REVIEW

**Comment by patrickjquinn** [comment]
We've actually moved to yarn full time, if you run npm for installing modules, you break the yarn build system (the yarn lock file gets out of sync) and hence why we aren't supporting npm officially with this project

**Comment by patrickjquinn** [comment]
However yarn isn't available on Raspberry Pi so if you look at that repo, you'll see npm is used for the automatic interallrr script :)

**Comment by syzer** [comment]
i do run this project on mac on npm.. so would be good to tell users that yarn is not required, right?

**Comment by patrickjquinn** [comment]
Well I dont want to put something in the project that isnt supported. If people run into issues with NPM at some stage, then i'll be the one dealing with it :) Limiting what cant go wrong is the best way to limit what does go wrong! Also Yarn is a superior build system so I see no reason switch back!

BUT if you really feel that people deserve to know about the alternative then i'm happy to merge 👍

**Comment by syzer** [comment]
we can support it.. its not different from npm :)

**Pull request merged**
