### PR TITLE
Update Readme with Required modules of Node.JS to run BRAIN

### PR DESCRIPTION
**Pull request by MrGate**
this is a list of modules required in case someone gets stuck trying to setup Brain. I'll be helping more in the future :)

### CODE REVIEW

**Comment by patrickjquinn** [comment]
Hey @MrGate  Just wondering why people need to know what the required modules are? Surly yarn install takes care of all this (We are using Yarn instead of npm), also this would appear to be windows only?

Thanks!

Pat.

**Comment by MrGate** [comment]
I was not awear, i did not look at yarn. Feel free to close this. 

Also are you planning on taking this project further then it is ? In about a week i got about 4 months and i can help out. I'm skilled in c, c#, javasceipt, html, css, node.js etc..

Also got a raspberry pi and will look forward to working on that repo also....

**Comment by MrGate** [comment]
Anyway i can directly contact you so we can discuss this project and what i can help with you???

I'm not some crap dev btw :) I work professionally in the healthcare field as a programmer and systems admin. I'm very good on documentation and commenting my code for future devs.

**Comment by patrickjquinn** [comment]
Sorry for the delay if you want to get in touch with me directly you can do so via pat64.ai@gmail.com :)

**Pull request closed without merging**
