### PR TITLE
Added admins and settings API

### PR DESCRIPTION
**Pull request by timstableford**
Hi Pat,

This adds some additional API's so I thought you might want to take a look.

Changelist:
- Added concept of admins and updated password.js
- Added API's to get and set all the settings.
- Added logout API.

### CODE REVIEW

**Comment by patrickjquinn** [comment]
Hey Tim,

Running through this code now (Sorry about the delay, iOS client is nearly 1-1 with the Android client now :) ) and i'll report back if I find anything conversation worthy!

In other news, i'll be starting up the wiki timeline page where we can start to flesh out a pipeline for the project today!

**Comment by timstableford** [comment]
Glad to hear you're still alive and the iOS client is coming along nicely.

I look forward to seeing your plans. I've added a few things that occurred to me to the roadmap, feel free to remove any if they don't fit your vision.

**Comment by patrickjquinn** [comment]
Excellent! Will do! 

My Plan is to get this on a hosted environment by tomorrow and add a remote P-Brain.ai server option to the iOS client. 

From there i'll start performing public case studies on Siri, Alexa & Google assistant in order to figure out what they do that we dont and put a structured roadmap around that + anything else deem essential additions.

**Comment by timstableford** [comment]
If that's your plan I'll implement the promiscuous logins this evening for your server. I suspect you won't need my help, but I've setup a local copy using an Apache proxy for SSL (with certificates from LetsEncrypt) if you do.
Sounds like a good plan :+1:

**Comment by patrickjquinn** [comment]
In `./P-Brain.ai/sqlite_db/index.js:129   row.is_admin = row.is_admin == 1` this seems to be throwing the error `TypeError: Cannot read property 'is_admin' of undefined` due to a null row being returned from SQL...any thoughts?

**Comment by timstableford** [comment]
How did you cause that to come about? Anyway, if no user is found then row is undefined, so I've added a check to make sure row is not undefined and pushed it to master. Let me know if that fixes the problem.

**Comment by patrickjquinn** [comment]
Tried logging in with an unrecognised user. The default behavior is to create a new account when the user doesn't exist correct?

**Comment by timstableford** [comment]
Nope. In master currently the correct behaviour is to send 401, unauthorized to the client. The PR I created earlier adds the ability to create users in this fashion.

**Pull request merged**
